_prefs: 
  mapid: ''
  saveCenter: true
_properties: {}
attribution: ''
bounds: 
  - -180
  - -85.0511
  - 180
  - 85.0511
center: 
  - 13.3401
  - 52.5009
  - 12
description: ''
format: "png8:m=h"
interactivity_layer: ''
layers: null
maxzoom: 16
minzoom: 0
name: ''
source: "tmsource:///Users/sebastianmeier/green_labels.tm2source"
styles: 
  - style.mss
template: ''
